/**
 * One entry per route: the text the search scores against.
 *
 * The template's index was generated by _extract/search-index.mjs from the
 * original Framer site. This one is maintained by hand, because the copy now
 * comes from the Association and its data files rather than from a scrape.
 * Alumni profile pages are deliberately absent: they are `noindex` on the
 * public site, so they are not offered as search results either.
 */
import type { SearchEntry } from '@/lib/search';
import { alumniEvents, featuredEvent, eventsPage } from '@/data/pages/events';
import { pillars, pillarsHeading, history, why, college, bannerLead } from '@/data/pages/about';
import { exploreItems } from '@/data/explore';
import { faq } from '@/data/pages/contact';
import { contact, footerColumns, mobileMenu } from '@/data/site';

const NAV = mobileMenu.map((link) => link.label);
const FOOTER = [
  ...footerColumns.flatMap((column) => [column.title, ...column.links.map((link) => link.label)]),
  contact.officeLabel,
  contact.address.filter(Boolean).join(' '),
  contact.emailLabel,
  contact.email,
  contact.phone,
  'Nihil Ultra',
];

const DESCRIPTION =
  "The alumni platform of the St. Xavier's College Alumni Association: a searchable directory of Xaverians, alumni stories, chapters, events and a private way to request a connection with a fellow Xaverian.";

export const searchIndex: SearchEntry[] = [
  {
    url: '/',
    title: 'Home',
    description: DESCRIPTION,
    h1: ["St. Xavier's College"],
    h2: [
      'About SXCCAA',
      'The Xaverian community',
      'Explore the Xaverian network',
      'Inside the Xaverian experience',
    ],
    h3: [
      'Alumni',
      'Chapters',
      'Initiatives',
      ...exploreItems.map((item) => item.title),
      'Campus',
      'Academics',
      'Culture & Community',
    ],
    h4: [],
    h5: [],
    h6: [],
    p: [
      ...NAV,
      "St. Xavier's College (Autonomous) · Kolkata",
      "A lifetime of connections. The St. Xavier's College Alumni Association brings Xaverians together to reconnect with their alma mater, celebrate their journeys and strengthen the community beyond the campus.",
      'Explore Alumni',
      'Discover SXCCAA',
      ...FOOTER,
    ],
  },
  {
    url: '/events',
    title: 'Alumni Events & Activities',
    description: eventsPage.intro,
    h1: [`${eventsPage.titleLead} ${eventsPage.titleTail} ${eventsPage.display.join(' ')}`],
    h2: [featuredEvent.title],
    h3: alumniEvents.map((event) => event.title),
    h4: [],
    h5: [],
    h6: [],
    p: [
      ...NAV,
      eventsPage.intro,
      eventsPage.photoNote,
      `${featuredEvent.date} ${featuredEvent.place}`,
      featuredEvent.description,
      ...alumniEvents.map((event) => `${event.date} ${event.place}`),
      ...alumniEvents.map((event) => event.description),
      ...FOOTER,
    ],
  },
  {
    url: '/about',
    title: 'About SXCCAA',
    description: DESCRIPTION,
    h1: ['About', 'the', 'Association'],
    h2: [
      'About SXCCAA',
      ...pillarsHeading.lines,
      ...history.lines,
      ...why.lines,
      ...college.lines,
    ],
    h3: [
      ...pillars.map((pillar) => pillar.title),
      ...history.milestones.map((milestone) => milestone.title),
      ...why.reasons.map((reason) => reason.title),
      ...college.marks,
    ],
    h4: [],
    h5: [],
    h6: [],
    p: [
      ...NAV,
      'A community that carries the Xaverian spirit forward. SXCCAA connects Xaverians through fellowship, initiatives and engagement with their alma mater, strengthening the bond between alumni and the College.',
      bannerLead.eyebrow,
      bannerLead.lead,
      bannerLead.text,
      'Established',
      'Students',
      'NIRF India Ranking 2025',
      ...pillars.flatMap((pillar) => [pillar.summary, ...pillar.points]),
      history.intro,
      ...history.milestones.map((milestone) => `${milestone.year} ${milestone.text}`),
      ...why.reasons.map((reason) => reason.text),
      college.lead,
      college.motto.latin,
      college.motto.gloss,
      ...college.facts.map((fact) => `${fact.label} ${fact.value}`),
      ...FOOTER,
    ],
  },
  {
    url: '/alumni',
    title: 'Alumni Directory',
    description: 'Search the SXCCAA alumni directory by name, company, designation or location, and filter by graduation year, programme, department, industry and city.',
    h1: ['Meet the', 'Xaverian', 'Community'],
    h2: ['Xaverians making a difference', 'Meet the Xaverian community'],
    h3: [],
    h4: [],
    h5: [],
    h6: [],
    p: [
      ...NAV,
      'Explore the journeys, professions and experiences of Xaverians across generations.',
      'Search by name, company, designation or location',
      'Graduation year',
      'Programme',
      'Department',
      'Industry',
      'Location',
      'Open to connect',
      'View profile',
      'Connect with this Alumnus',
      'Email addresses and phone numbers are never shown here. To reach an alumnus, send a connection request and the Association will pass it on.',
      ...FOOTER,
    ],
  },
  {
    url: '/explore',
    title: 'Explore the Xaverian Network',
    description: 'The alumni directory, stories, chapters, events, community initiatives and the connection request — everything SXCCAA offers Xaverians in one place.',
    h1: ['Explore the', 'Xaverian', 'Network'],
    h2: [],
    h3: exploreItems.map((item) => item.title),
    h4: [],
    h5: [],
    h6: [],
    p: [...NAV, ...exploreItems.map((item) => item.description), 'Explore', ...FOOTER],
  },
  {
    url: '/contact',
    title: 'Contact SXCCAA',
    description: 'Get in touch with the St. Xavier’s College Alumni Association about the alumni directory, chapters, events or Association initiatives.',
    h1: ['Contact'],
    h2: ['Stay connected with SXCCAA', 'FAQS'],
    h3: faq.map((item) => item.question),
    h4: [],
    h5: [],
    h6: [],
    p: [
      ...NAV,
      'Have a question, or want to reconnect with the Xaverian community? Whether it is the alumni directory, a chapter, an Association initiative or an event, our team is here to help.',
      contact.phone,
      contact.email,
      'Follow Us -',
      'Full name*',
      'Email*',
      'Message',
      'Send Message',
      ...faq.map((item) => item.answer),
      ...FOOTER,
    ],
  },
  {
    url: '/privacy-policy',
    title: 'Privacy Policy',
    description: 'How the SXCCAA alumni platform treats personal data: contact details are never published, and every record carries visibility and consent flags.',
    h1: ['Privacy Policy'],
    h2: [],
    h3: [],
    h4: [],
    h5: [],
    h6: [],
    p: [...NAV, 'consent', 'visibility', 'noindex', 'connection request', 'personal data', ...FOOTER],
  },
  {
    url: '/terms-of-use',
    title: 'Terms of Use',
    description: 'The terms the SXCCAA alumni directory and connection-request feature are built to enforce.',
    h1: ['Terms of Use'],
    h2: [],
    h3: [],
    h4: [],
    h5: [],
    h6: [],
    p: [...NAV, 'directory', 'scraping', 'moderation', 'rate limiting', ...FOOTER],
  },
];
